name: APITransformer
on: [push]

jobs:
  Test_Transformer:
    runs-on: ubuntu-latest
    name: Testing API Transformer Action
    steps:
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: APIMATIC Transformer
        uses: apimatic/apimatic-transformer-action@v0.1
        id: raml
        with:
         auth: ${{ secrets.AUTH }}
         inputURL: 'https://petstore.swagger.io/v2/swagger.json'
         exportFormat: 'apimatic'
     # Use the Transformed API Spec as output from our action (id:raml)
      - name: Get the API Spec URL
        run: echo "${{ steps.raml.outputs.specurl }}"
        
      - name: APIMATIC Transformer
        uses: apimatic/apimatic-transformer-action@v0.1
        id: wsdl
        with:
         auth: ${{ secrets.AUTH }}
         inputURL: 'https://petstore.swagger.io/v2/swagger.json'
         exportFormat: 'wsdl'
     # Use the Transformed API Spec as output from our action (id:raml)
      - name: Get the API Spec URL
        run: echo "${{ steps.wsdl.outputs.specurl }}"
